### ISSUE TITLE
Issue when reusing the webpack config of examples/simples in examples/simples-bs

### ISSUE THREAD

**Issue by kopax** [marmelab/admin-on-rest#1744]
We have been trying to prepare our `ra-ui-bootstrap-styled` package for v2.

We wanted to maintain it with a fork, using the react-admin lerna workspace, we:

- copied `react-admin` into `react-admin-bs` to export Admin and Resource with `ra-ui-bootstrap-styled` instead of `ra-ui-material-ui`
- copied `ra-ui-material-ui` into `ra-ui-bootstrap-styled`
- copied `simple` into `simple-bs`
- edited the webpack.config.js to resolve both `react-admin-bs` and `ra-ui-bootstrap-styled`
- edited the dependecies in `simple-bs`.
- edited `Makefile` to add : 

        run-simple-bs: ## run the simple example bootstrap-styled
        	@cd examples/simple-bs && yarn start

It seems that webpack doesn't like multiple configured packages with lerna.

```bash
 ./node_modules/.bin/webpack-dev-server --progress --color --hot --watch --mode development
The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D
module.js:559
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dka/workspace/github.com/yeutech/react-admin/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)
error An unexpected error occurred: "Command failed.
```

Are you aware of that bug? It seems to come from webpack.

As soon as I do `mv examples/simple-bs ..` and run `yarn && make run` , it works again.

I am just trying to get information on the workspace/build environment. 

Is this why you installed the dependencies from npm for the **demo** and others examples projects?

**Comment by kopax** [comment]
Adding to root package the following solved our issue:

        "webpack": "~4.5.0",
        "webpack-cli": "~2.0.13",
        "webpack-dev-server": "~3.1.1",
