### ISSUE TITLE
Spinning <SaveButton>

### ISSUE THREAD

**Issue by vlameiras** [marmelab/admin-on-rest#237]
I've upgraded to 0.7.0 and added the new SimpleForm to my existing Create\Edit components and I started having some issues with the SaveButton. 
When I try to submit a new form and I miss one of the validation conditions the field is correctly highlighted, however if I press the save button a second time it stays spinning forever.
I'm also getting a permanent spinning SaveButton on every HTTP request that doesn't return a Success code (I'm using the simple.js REST client example provided)

**Comment by vlameiras** [comment]
Not sure if this is related, but when I try to update a date using a DateInput I also get a spinning SaveButton. The HTTP requests goes through, but like on my first report it keeps spinning forever.

Here is my DateInput code:

```
<DateInput source="dataNascimento" label="Data de Nascimento" options={{
	mode: 'portrait',
	hintText: 'Escolha uma data',
	okLabel: 'OK',
	cancelLabel: 'Cancelar',
}} />

```
I get the following errors on Chrome console:

```
uncaught at handleFetch Invariant Violation: Objects are not valid as a React child (found: Sat Jan 28 2012 00:00:00 GMT+0000 (Hora padrão de GMT)). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `TextField`.
    at invariant (http://localhost:3000/static/js/bundle.js:11356:16)
    at traverseAllChildrenImpl (http://localhost:3000/static/js/bundle.js:27348:24)
    at traverseAllChildren (http://localhost:3000/static/js/bundle.js:27376:11)
    at Object.instantiateChildren (http://localhost:3000/static/js/bundle.js:25564:8)
    at ReactDOMComponent._reconcilerInstantiateChildren (http://localhost:3000/static/js/bundle.js:25116:42)
    at ReactDOMComponent.mountChildren (http://localhost:3000/static/js/bundle.js:25155:28)
    at ReactDOMComponent._createInitialChildren (http://localhost:3000/static/js/bundle.js:22172:33)
    at ReactDOMComponent.mountComponent (http://localhost:3000/static/js/bundle.js:21991:13)
    at Object.mountComponent (http://localhost:3000/static/js/bundle.js:18430:36)
    at Object.obj.(anonymous function) [as mountComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8386:20)

2017-01-19 15:33:53.519 utils.js:201 uncaught at handleFetch TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (http://localhost:3000/static/js/bundle.js:18447:29)
    at ReactCompositeComponentWrapper.getHostNode (http://localhost:3000/static/js/bundle.js:26175:29)
    at Object.getHostNode (http://localhost:3000/static/js/bundle.js:18447:30)
    at Object.updateChildren (http://localhost:3000/static/js/bundle.js:25607:49)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:3000/static/js/bundle.js:25137:33)
    at ReactDOMComponent._updateChildren (http://localhost:3000/static/js/bundle.js:25241:32)
    at ReactDOMComponent.updateChildren (http://localhost:3000/static/js/bundle.js:25228:13)
    at ReactDOMComponent._updateDOMChildren (http://localhost:3000/static/js/bundle.js:22411:13)
    at ReactDOMComponent.updateComponent (http://localhost:3000/static/js/bundle.js:22229:11)
    at ReactDOMComponent.receiveComponent (http://localhost:3000/static/js/bundle.js:22191:11)
'''
