### ISSUE TITLE
SaveButton spinning forever with DateInput update

### ISSUE THREAD

**Issue by vlameiras** [marmelab/admin-on-rest#243]
When I try to update a date using a DateInput I also get a spinning SaveButton. The PUT request goes through, but the button keeps spinning and sometimes it just freezes and I have to make page refresh so I can resume navigation.

Here is my DateInput code:

```
<DateInput source="dataNascimento" label="Data de Nascimento" options={{
	mode: 'portrait',
	hintText: 'Escolha uma data',
	okLabel: 'OK',
	cancelLabel: 'Cancelar',
}} />

```
I get the following errors on Chrome console:

```
uncaught at handleFetch Invariant Violation: Objects are not valid as a React child (found: Sat Jan 28 2012 00:00:00 GMT+0000 (Hora padrão de GMT)). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `TextField`.
    at invariant (http://localhost:3000/static/js/bundle.js:11356:16)
    at traverseAllChildrenImpl (http://localhost:3000/static/js/bundle.js:27348:24)
    at traverseAllChildren (http://localhost:3000/static/js/bundle.js:27376:11)
    at Object.instantiateChildren (http://localhost:3000/static/js/bundle.js:25564:8)
    at ReactDOMComponent._reconcilerInstantiateChildren (http://localhost:3000/static/js/bundle.js:25116:42)
    at ReactDOMComponent.mountChildren (http://localhost:3000/static/js/bundle.js:25155:28)
    at ReactDOMComponent._createInitialChildren (http://localhost:3000/static/js/bundle.js:22172:33)
    at ReactDOMComponent.mountComponent (http://localhost:3000/static/js/bundle.js:21991:13)
    at Object.mountComponent (http://localhost:3000/static/js/bundle.js:18430:36)
    at Object.obj.(anonymous function) [as mountComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8386:20)

2017-01-19 15:33:53.519 utils.js:201 uncaught at handleFetch TypeError: Cannot read property 'getHostNode' of null
    at Object.getHostNode (http://localhost:3000/static/js/bundle.js:18447:29)
    at ReactCompositeComponentWrapper.getHostNode (http://localhost:3000/static/js/bundle.js:26175:29)
    at Object.getHostNode (http://localhost:3000/static/js/bundle.js:18447:30)
    at Object.updateChildren (http://localhost:3000/static/js/bundle.js:25607:49)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:3000/static/js/bundle.js:25137:33)
    at ReactDOMComponent._updateChildren (http://localhost:3000/static/js/bundle.js:25241:32)
    at ReactDOMComponent.updateChildren (http://localhost:3000/static/js/bundle.js:25228:13)
    at ReactDOMComponent._updateDOMChildren (http://localhost:3000/static/js/bundle.js:22411:13)
    at ReactDOMComponent.updateComponent (http://localhost:3000/static/js/bundle.js:22229:11)
    at ReactDOMComponent.receiveComponent (http://localhost:3000/static/js/bundle.js:22191:11)
'''

**Comment by fzaninotto** [comment]
Can't reproduce the issue, which version of admin-on-rest are you using?

**Comment by vlameiras** [comment]
I'm using 0.7.1 and it was already happening with 0.7.0 but I think it
worked properly with 0.6.2. I'll try to rollback and test it further

Thanks

**Comment by fzaninotto** [comment]
Are you using a custom REST client?

The issue isn't just with the save button, and I don't think it is with the Date Input either, since I can't reproduce it. Can you try and make a simple admin based on admin-on-rest's example showing the bug.

**Comment by vlameiras** [comment]
I'm using the simple REST client example provided on the tutorial, just
slightly changed to support some different response headers

I will try to have my implementation online tomorrow. I'll keep you posted

**Comment by vlameiras** [comment]
I've put it temporarily online so you can check it out

http://51.15.129.184:3000/

**Comment by fzaninotto** [comment]
I can reproduce the error but not debug it, since your code is transpiled and bundled. Could you paste the full `<Edit>` component configuration?

**Comment by vlameiras** [comment]
Sorry about that. Here's the code:

```
export const UtentesEdit = (props) => (
    <Edit title={<UtentesEditTitle />} {...props}>
        <TabbedForm>
            <FormTab label="Dados Pessoais" icon={<Person />}>
                <FullNameInput />
                <DateInput source="dataNascimento" label="Data de Nascimento" options={{
                    mode: 'portrait',
                    hintText: 'Escolha uma data',
                    okLabel: 'OK',
                    cancelLabel: 'Cancelar',
                }} elStyle={styles.dataNascimento}/>
                <SelectInput label="Género" source="genero" choices={[
                    { id: 'F', name: 'Feminino' },
                    { id: 'M', name: 'Masculino' },
                ]} elStyle={styles.genero} />
            </FormTab>
            <FormTab label="Contactos" icon={<Phone />}>
                <NumberInput label="Telefone" source="telefone" style={{ display: 'inline-block' }} />
                <TextInput label="Email" source="email" type="email" style={{ display: 'inline-block', marginLeft: 32 }} />
            </FormTab>
            <FormTab label="Morada" icon={<LocationCity />}>
                <TextInput label="Rua" source="morada.rua" elStyle={styles.rua} />      
                <TextInput label="Localidade" source="morada.localidade" style={{ display: 'inline-block' }}/>
                <CodigoPostalInput style={{ display: 'inline-block', marginLeft: 32 }}/>
            </FormTab>
            <FormTab label="Notas" icon={<Comment />}>
                <RichTextInput source="notas" addLabel={false} style={{marginTop: 32}}/>    
            </FormTab>    
            <FormTab label="Histórico" icon={<History />}>
              
            </FormTab>   
        </TabbedForm>
    </Edit>
);
```

I'm using a custom FullNameInput, here's the full code as wel:


```
const renderTextField = ({ input, label, meta: { touched, error }, ...custom }) => (
    <TextField
        hintText={label}
        floatingLabelText={label}
        errorText={touched && error}
        {...input}
        {...custom}
    />
);

const FullNameInput = () => (
    <span>
        <Field name="nome" component={renderTextField} type="text" label="Nome" style={{ display: 'inline-block' }} />  
        <Field name="apelido" component={renderTextField} type="text" label="Apelido" style={{ display: 'inline-block', marginLeft: 32 }}/>
    </span>
);
export default FullNameInput;
```

**Comment by fzaninotto** [comment]
Can you reproduce the bug with just:

```js
export const UtentesEdit = (props) => (
    <Edit {...props}>
        <TabbedForm>
            <FormTab label="Dados Pessoais" icon={<Person />}>
                <DateInput source="dataNascimento" label="Data de Nascimento" options={{
                    mode: 'portrait',
                    hintText: 'Escolha uma data',
                    okLabel: 'OK',
                    cancelLabel: 'Cancelar',
                }} elStyle={styles.dataNascimento}/>
            </FormTab>   
        </TabbedForm>
    </Edit>
);
```

If yes, does the following also trigger the problem?

```js
```js
export const UtentesEdit = (props) => (
    <Edit {...props}>
        <TabbedForm>
            <FormTab label="Dados Pessoais" icon={<Person />}>
                <DateInput source="dataNascimento" label="Data de Nascimento" />
            </FormTab>   
        </TabbedForm>
    </Edit>
);
```

?

**Comment by vlameiras** [comment]
I tried that and the problem still occured. However, I just stripped the code to the bare minimum and it works now!

```
import React from 'react';
import { List, Datagrid, EditButton, Edit, DateInput, TabbedForm, FormTab } from 'admin-on-rest/lib/mui';

export const UtentesList = (props) => (
    <List title="Utentes" {...props} >
        <Datagrid>
            <EditButton />
        </Datagrid>
    </List>

);

export const UtentesEdit = (props) => (
    <Edit {...props}>
        <TabbedForm>
            <FormTab label="Dados Pessoais">
                <DateInput source="dataNascimento" label="Data de Nascimento" />
            </FormTab>   
        </TabbedForm>
    </Edit>
);
```

I'll re-add the code step-by-step and see if I can see where the problem resides.

**Comment by vlameiras** [comment]
I've found the cause, its this TextField on the List component which was bound to a date

`<TextField label="Data de Nascimento" source="dataNascimento" />`

Changed it to DateField and it works now. 

Thank you!
