### ISSUE TITLE
"npm test" failed at first tutorial step

### ISSUE THREAD

**Issue by FallDi** [marmelab/admin-on-rest#270]
Hello!

I following tutorial and complete following steps
1) https://github.com/marmelab/admin-on-rest/blob/master/docs/Tutorial.md#admin-on-rest-tutorial
2) https://github.com/marmelab/admin-on-rest/blob/master/docs/Tutorial.md#installation
3) https://github.com/marmelab/admin-on-rest/blob/master/docs/Tutorial.md#making-contact-with-the-api

I run npm test and it crashed with following errors

```
FAIL  src/App.test.js (5.555s)
  ● renders without crashing

    TypeError: Cannot read property 'removeItem' of undefined

      at Object.saveState (node_modules/history/lib/DOMStateStorage.js:26:28)
      at finishTransition (node_modules/history/lib/createHashHistory.js:125:24)
      at node_modules/history/lib/createHistory.js:157:13
      at node_modules/history/lib/createHistory.js:133:9
      at next (node_modules/history/lib/AsyncUtils.js:53:7)
      at Object.loopAsync (node_modules/history/lib/AsyncUtils.js:57:3)
      at confirmTransitionTo (node_modules/history/lib/createHistory.js:119:17)
      at transitionTo (node_modules/history/lib/createHistory.js:145:5)
      at Object.replace (node_modules/history/lib/createHistory.js:172:5)
      at Object.replace (node_modules/history/lib/createHashHistory.js:187:13)
      at Object.replace (node_modules/history/lib/useBasename.js:109:15)
      at Object.replace (node_modules/history/lib/useQueries.js:119:15)
      at node_modules/react-router/lib/createTransitionManager.js:281:21
      at handleErrorOrRedirect (node_modules/react-router/lib/createTransitionManager.js:118:39)
      at finishEnterHooks (node_modules/react-router/lib/createTransitionManager.js:103:41)
      at next (node_modules/react-router/lib/AsyncUtils.js:46:16)
      at loopAsync (node_modules/react-router/lib/AsyncUtils.js:56:3)
      at runTransitionHooks (node_modules/react-router/lib/TransitionUtils.js:70:29)
      at runEnterHooks (node_modules/react-router/lib/TransitionUtils.js:93:10)
      at node_modules/react-router/lib/createTransitionManager.js:99:42
      at runTransitionHooks (node_modules/react-router/lib/TransitionUtils.js:50:5)
      at runChangeHooks (node_modules/react-router/lib/TransitionUtils.js:110:10)
      at finishMatch (node_modules/react-router/lib/createTransitionManager.js:96:41)
      at node_modules/react-router/lib/createTransitionManager.js:72:11
      at next (node_modules/react-router/lib/AsyncUtils.js:46:16)
      at loopAsync (node_modules/react-router/lib/AsyncUtils.js:56:3)
      at matchRoutes (node_modules/react-router/lib/matchRoutes.js:241:29)
      at match (node_modules/react-router/lib/createTransitionManager.js:68:33)
      at node_modules/react-router/lib/createTransitionManager.js:277:9
      at Object.listen (node_modules/react-router-redux/lib/sync.js:135:7)
      at Object.listen (node_modules/react-router/lib/createTransitionManager.js:273:20)
      at componentWillMount (node_modules/react-router/lib/Router.js:125:40)
      at node_modules/react-dom/lib/ReactCompositeComponent.js:348:23
      at measureLifeCyclePerf (node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:347:9)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at ReactCompositeComponentWrapper.performInitialMount (node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
      at ReactCompositeComponentWrapper.mountComponent (node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
      at Object.mountComponent (node_modules/react-dom/lib/ReactReconciler.js:46:35)
      at mountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:104:32)
      at ReactReconcileTransaction.perform (node_modules/react-dom/lib/Transaction.js:140:20)
      at batchedMountComponentIntoNode (node_modules/react-dom/lib/ReactMount.js:126:15)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:97:27)
      at Object._renderNewRootComponent (node_modules/react-dom/lib/ReactMount.js:320:18)
      at Object._renderSubtreeIntoContainer (node_modules/react-dom/lib/ReactMount.js:401:32)
      at Object.render (node_modules/react-dom/lib/ReactMount.js:422:23)
      at Object.<anonymous>.it (src/App.test.js:7:48)

  ✕ renders without crashing (41ms)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        8.964s
Ran all test suites.

Watch Usage
 › Press p to filter by a filename regex pattern.
 › Press q to quit watch mode.
 › Press Enter to trigger a test run.
```

**Comment by fzaninotto** [comment]
That's because the `<Admin>` component uses `history`, which is a *browser* module relying `window.sessionStorage`. This object is not available in the node environment, therefore the default test created by `create-react-app`, which runs in node and not in the browser, fails.

I'd say it's normal. Once equipped with a router, a React app must be unit tested within a browser. Individual components remain testable in Node.
